// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlmklWYrvp0R_cbC3uPgVkvWcZSMR19Bc',
    appId: '1:460322578843:web:84cfdd93c3823f7d16013e',
    messagingSenderId: '460322578843',
    projectId: 'slowaging',
    authDomain: 'slowaging.firebaseapp.com',
    storageBucket: 'slowaging.firebasestorage.app',
    measurementId: 'G-6NYCT0WFR7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9BKGx_QM887GOalw_Dyd-yLLOxcEQnOU',
    appId: '1:460322578843:android:74f6d826e1d40da316013e',
    messagingSenderId: '460322578843',
    projectId: 'slowaging',
    storageBucket: 'slowaging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqrPry-ZeN85EFNKJ4R_vRnhpvb_gfmcU',
    appId: '1:460322578843:ios:a89657f86cd3922016013e',
    messagingSenderId: '460322578843',
    projectId: 'slowaging',
    storageBucket: 'slowaging.firebasestorage.app',
    iosBundleId: 'com.example.mpczerocalorie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqrPry-ZeN85EFNKJ4R_vRnhpvb_gfmcU',
    appId: '1:460322578843:ios:a89657f86cd3922016013e',
    messagingSenderId: '460322578843',
    projectId: 'slowaging',
    storageBucket: 'slowaging.firebasestorage.app',
    iosBundleId: 'com.example.mpczerocalorie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlmklWYrvp0R_cbC3uPgVkvWcZSMR19Bc',
    appId: '1:460322578843:web:bd2f4bc8748ec19b16013e',
    messagingSenderId: '460322578843',
    projectId: 'slowaging',
    authDomain: 'slowaging.firebaseapp.com',
    storageBucket: 'slowaging.firebasestorage.app',
    measurementId: 'G-XNPFF4YVW7',
  );
}
